# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Gemfile", "Gemfile.lock", "changelog.md"]
markdown: kramdown
highlighter: pygments
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: DCgov Guides Template
subtitle: A Jekyll template for DC Government project documentation

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: '/guides-template'

# Author/Organization info to be displayed in the templates
author:
  name: The Office of Technology Innovation
  url: http://octo.dc.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/dc_logo.png
logoalt: The D.C. flag

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: ./
  internal: true
- text: Example Page
  url: example_page
  internal: true
- text: Glossary of Terms
  bookmark: true
  bookmark_class: glossary-toggle
- text: Edit this Repo
  url: https://github.com/cfpb/DOCter
  internal: false

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: guides-template
  description: 
  url: https://github.com/DCgov/guides-template

google_analytics_ua: 

# Style Variables
brand_color: "#DA253B"
